name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWD }}

      - name: Build and push Docker image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [ "$BRANCH_NAME" != "main" ]; then
            IMAGE_NAME="leeegiit/$BRANCH_NAME"
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME
          else
            echo "Skipping push for main branch"
          fi
